# Generated by Django 3.2.3 on 2021-06-11 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='emil',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMAIL', 'FEMAIL')], default='MALE', max_length=10),
            preserve_default=False,
        ),
    ]
